server:
  host:
    name: "localhost"
    port: 8080
database:
  path: "databases/tinyis.db"
super_organization:
  name : "root"
  admin:
    username: "admin"
    password: "admin"
crypto:
  jwt:
    path: "resources/crypto/jwt"
  server:
    key: "resources/crypto/server/server-key.pem"
    cert: "resources/crypto/server/server-cert.pem"
