server:
  host:
    name: "localhost"
    port: 8080
database:
  path: "/Users/thilinashashimalsenarath/tinydb.db"
super_organization:
  name : "root"
  admin:
    username: "admin"
    password: "admin"

